// ================= kits: the knob settings each factory pattern loads (INIT only for now) =================
// KIT is the base sound, CC values by shogun::Knobs name. STYLE[pattern name] overrides it for that pattern.
// Decays follow the engine's curve, tau = 8 ms * exp(4.5 u). A played voice that needs a body (kick, snare tone, toms,
// open hat, cowbell) is not set under CC 40 (33 ms), so no preset is a click. Hats, claves and maracas may be shorter.
// LEVEL is generated by web/make_levels.mjs: each voice's LEVEL knob so one hit peaks at its role's target on the main.
const KIT={bd1Attack:30,bd1Decay:55,bd1Pitch:45,bd1Tune:30,bd1Noise:0,bd1Filter:64,bd1Dist:0,bd1Trigger:0,bd2Tune:45,bd2Decay:45,bd2Tone:40,
  sdTune:55,sdDTune:76,sdPitch:30,sdTone:45,sdToneDecay:40,sdSnappy:95,sdSnDecay:40,rsTune:55,cpAttack:100,cpDecay:30,cpFilter:72,cpTrigger:0,cpData:48,
  clTune:70,clDecay:25,cyTune:70,cyTone:60,cyDecay:70,ohDecay:35,hhTune:75,hhDecay:25,ltcTune:45,ltcDecay:40,mtcTune:50,mtcDecay:40,htcTune:55,htcDecay:40,
  ltcNoise:0,mtcNoise:0,htcNoise:0,tomNoise:25,cbTune:52,cbDecay:40,maDecay:20,leadTone:70,bassTone:45};
const STYLE={
 "INIT":{}};   // factory kits cleared for now: INIT is the base KIT
// Peak on the main for one full-accent hit, by role. Kicks loudest, then snare and clap, toms, percussion, cymbals and hats.
const TARGET={BD1:.6,BD2:.6,SD:.5,CP:.5,LTC:.42,MTC:.42,HTC:.42,RS:.28,CL:.28,CB:.28,HH:.24,OH:.24,CY:.24,MA:.18,LEAD:.3,BASS:.42};
const kitOf=name=>Object.assign({},KIT,STYLE[name]||{});
const LEVEL=/*__LEVEL__*/{"INIT":{"BD1":0.642,"BD2":0.617,"SD":0.304,"RS":0.289,"CY":0.327,"OH":0.287,"HH":0.295,"CL":0.283,"CP":0.559,"LTC":0.466,"MTC":0.624,"HTC":0.447,"CB":0.614,"MA":0.518,"LEAD":0.757,"BASS":1}};
