#pragma once
// Generated by scripts/gen_halfband.py. Do not edit.
// Stage 1 (2fs -> fs): the shared exact halfband jidai::dsp::Halfband93 (jidai/dsp/Halfband.h), 93 taps,
// delay 46 samples at 2fs = 23 base samples.
// Stage 2 (4fs -> 2fs): 25 taps, stopband 123.11 dB, pass ripple 1.24e-05 dB. Delay 12 samples at 4fs = 3 base samples.
namespace shogun { namespace hb {
constexpr int kStage2Taps = 25;
constexpr double kStage2[25] = {
    -5.41818364681034883e-07,
    -2.10200146495198581e-04,
    4.39213565403218112e-06,
    1.83293414034374274e-03,
    -1.75523916994357895e-05,
    -8.45598040422967934e-03,
    4.57514776366707573e-05,
    2.78905401054767230e-02,
    -8.64902085974428335e-05,
    -7.93774405120983850e-02,
    1.24735354273890502e-04,
    3.08319809938207789e-01,
    4.99859410902333656e-01,
    3.08319809938207789e-01,
    1.24735354273890502e-04,
    -7.93774405120983850e-02,
    -8.64902085974428335e-05,
    2.78905401054767230e-02,
    4.57514776366707573e-05,
    -8.45598040422967934e-03,
    -1.75523916994357895e-05,
    1.83293414034374274e-03,
    4.39213565403218112e-06,
    -2.10200146495198581e-04,
    -5.41818364681034883e-07,
};
}  // namespace hb
}  // namespace shogun
