#pragma once

// Wave: the Serge middle-section folder, six identical cells in series.
// Ported from martialsystems/serge_middle (SergeMiddle/dsp/WaveMiddle.h and WaveMiddleTables.h), the cell, the
// Lambert W solver, and the drive peak table, unchanged. Not ported: the 4x oversampler, the DC block, and the
// knob smoother. Copyright (c) 2026 Martial Systems LLC.

#include <cmath>

namespace shogun {
namespace wave {

// Shockley parameters for one cell, the v1 lock.
constexpr double kVT = 0.02585;
constexpr double kIs = 2.52e-9;
constexpr double kEta = 1.68;
constexpr double kR = 33000.0;
constexpr int kCells = 6;
constexpr double kGMin = 0.5;
constexpr double kGMax = 8.0;
constexpr double kAudioFullScaleVolts = 5.0;
constexpr double kFullScalePeakVin = 4.7072868603604885;
constexpr double kOutputGain = 4.3792716960440945;
constexpr double kEtaVT = kEta * kVT;

// P(g): the peak of |C^6(v)| for |v| <= 5 g, linear in g between knots. Generated by serge_middle tools/gen_tables.py.
constexpr int kDrivePeakCount = 53;

constexpr double kDrivePeakG[53] = {
  0.5,
  0.5474003977393376,
  0.5497340568500901,
  0.5521767654519992,
  0.5547067136468338,
  0.5573675212310563,
  0.5601591882046668,
  0.5630599046694339,
  0.566091480523589,
  0.5692102959706695,
  0.7307789759456843,
  0.7332654411052391,
  0.7358191080258628,
  0.7384623772945786,
  0.7411952489113867,
  0.7440401234633096,
  0.7469970009503477,
  0.7500434807854778,
  0.7531795629687,
  0.9185864093019299,
  0.9213309248495607,
  0.9240983113600885,
  0.9268885688335132,
  0.9297016972698348,
  0.9325605676319503,
  0.9354651799198596,
  0.9384384050964597,
  0.9414573721988535,
  1.0,
  1.1099886913655106,
  1.1168787026741451,
  1.1306587252914142,
  1.144438747908683,
  1.1582187705259521,
  1.1788888044518555,
  1.1995588383777591,
  1.2340088949209316,
  1.2753489627727383,
  1.3304690532418142,
  1.4062591776367936,
  1.509609347266311,
  1.5853994716612905,
  1.6749696186735388,
  1.792099810920325,
  1.943680059710284,
  2.0,
  2.1503803989693187,
  2.4466508852406017,
  2.894501620301843,
  3.617952807708465,
  4.0,
  4.954615001583555,
  8.0,
};

constexpr double kDrivePeakP[53] = {
  0.1775277872935283,
  0.1775277872935283,
  0.1801083216190401,
  0.1823810649417758,
  0.1843095472151966,
  0.18591382561662023,
  0.18717748565229037,
  0.18808406500314873,
  0.18863517809647518,
  0.18881896732707976,
  0.18881896732707976,
  0.19231787361341546,
  0.19538316727663818,
  0.19801606632845936,
  0.20019412313069718,
  0.20191527290684846,
  0.20316031609079727,
  0.20391057268140328,
  0.20416215561354206,
  0.20416215561354206,
  0.2096438416071082,
  0.21449114855650264,
  0.21865434960366537,
  0.22209582167109465,
  0.22480970979773496,
  0.22676595163237234,
  0.2279533761144198,
  0.22834847193959784,
  0.22834847193959784,
  0.22834847193959784,
  0.2538347487518584,
  0.30541809576153445,
  0.3577434904844825,
  0.41073672590994126,
  0.49134440207063745,
  0.573141728721227,
  0.7117458228533513,
  0.8812349685007477,
  1.1115937204565158,
  1.43480382544928,
  1.8847703095863748,
  2.2199965883279056,
  2.6207186070952035,
  3.1507658632937945,
  3.8447414237834288,
  4.104493885791202,
  4.80224901460087,
  6.191140686600411,
  8.315964343499907,
  11.78910827317095,
  13.636725832047457,
  18.279866505401003,
  33.228577867627834,
};

inline double logK() {
  static const double v = std::log((kIs * kR) / kEtaVT);
  return v;
}

// Seed for the principal branch. logZ is ln of the W argument.
inline double w0Initial(double logZ) {
  if (logZ < -2.0) {
    const double z = std::exp(logZ);
    const double z2 = z * z;
    return z - z2 + 1.5 * z2 * z - (8.0 / 3.0) * z2 * z2;
  }
  if (logZ < 1.0) {
    const double z = std::exp(logZ);
    return z / (1.0 + z);
  }
  const double l2 = std::log(logZ);
  return logZ - l2 + l2 / logZ;
}

// Principal Lambert W of (Is R)/(eta VT) * exp(|v|/(eta VT)). Halley on w + ln(w) - ln(z) = 0; the product
// k * exp(|v| / (eta VT)) is never formed, so it does not overflow at the top of the drive range.
inline double lambertW0KExp(double absV) {
  const double logZ = absV / kEtaVT + logK();
  double w = w0Initial(logZ);
  if (!(w > 0.0)) {
    w = std::exp(logZ < 0.0 ? logZ : 0.0);
    if (w <= 0.0) w = 1e-300;
  }
  const double scale = std::fabs(logZ) > 1.0 ? std::fabs(logZ) : 1.0;
  for (int i = 0; i < 8; ++i) {
    const double f = w + std::log(w) - logZ;
    if (std::fabs(f) <= 1e-14 * scale) return w;
    const double invW = 1.0 / w;
    const double fp = 1.0 + invW;
    // f'' = -1/w^2, so the Halley denominator is fp + f/(2 fp w^2).
    const double step = f / (fp + f * (invW * invW) / (2.0 * fp));
    double wNext = w - step;
    if (!(wNext > 0.0)) wNext = 0.5 * w;
    if (wNext == w) return w;
    w = wNext;
  }
  return w;
}

// One stage. v_out = sign(v) * (|v| - 2 eta VT W(z)), v_out(0) = 0.
inline double cell(double v) {
  if (v == 0.0) return 0.0;
  const double mag = std::fabs(v);
  const double out = mag - 2.0 * kEtaVT * lambertW0KExp(mag);
  return v < 0.0 ? -out : out;
}

// y = C(C(C(C(C(C(v)))))).
inline double stack(double v) {
  for (int i = 0; i < kCells; ++i) v = cell(v);
  return v;
}

inline double drivePeak(double g) {
  if (g < kGMin) g = kGMin;
  if (g > kGMax) g = kGMax;
  if (g <= kDrivePeakG[0]) return kDrivePeakP[0];
  const int last = kDrivePeakCount - 1;
  if (g >= kDrivePeakG[last]) return kDrivePeakP[last];
  int lo = 0;
  int hi = last;
  while (hi - lo > 1) {
    const int mid = (lo + hi) / 2;
    if (kDrivePeakG[mid] <= g) lo = mid;
    else hi = mid;
  }
  const double t = (g - kDrivePeakG[lo]) / (kDrivePeakG[hi] - kDrivePeakG[lo]);
  return kDrivePeakP[lo] + t * (kDrivePeakP[hi] - kDrivePeakP[lo]);
}

// OUTPUT_GAIN * P(1) / P(g): a full-scale input peaks at 1 after the cells at any g.
inline double outputScale(double g) { return kOutputGain * drivePeak(1.0) / drivePeak(g); }

// Wave knob: CC 0 is bypass. CC 1 is g = 0.5, CC 127 is g = 4, linear between. STAND-IN taper.
inline double driveOf(int cc) {
  if (cc <= 0) return 0.0;
  if (cc > 127) cc = 127;
  return 0.5 + 3.5 * static_cast<double>(cc - 1) / 126.0;
}

// The body sample x, about +/-1, scaled to +/-5 V, folded, and brought back to the voice level.
// The serge_middle audio_map with both filters bypassed. Wave CC 0 returns x unchanged.
inline double fold(double x, int waveCc) {
  if (waveCc <= 0) return x;
  const double g = driveOf(waveCc);
  return outputScale(g) * stack(kAudioFullScaleVolts * g * x);
}

}  // namespace wave
}  // namespace shogun
