#!/usr/bin/env python3
"""Export the 200 random LEVEL COMP settings of verify_folder.py (numpy default_rng(7), same draw order) so the
C++ testWaveLevelComp runs exactly the settings the spec's numbers came from. Writes tests/data/levelcomp_cases.h."""
import numpy as np
from pathlib import Path
rng = np.random.default_rng(7)
rows = []
for t in range(200):
    amts = list(rng.uniform(0, 1, 3)); syms = list(rng.uniform(-1, 1, 3) * (rng.uniform() < 0.5))
    amp = float(rng.choice([1.0, 0.6, 0.3])); f = float(rng.uniform(60, 400))
    rows.append(amts + syms + [amp, f])
out = ["#pragma once", "// Generated by scripts/gen_levelcomp_cases.py from verify_folder.py's rng (seed 7). Do not edit.",
       "// a1 a2 a3 sym1 sym2 sym3 amp f", "constexpr double kLevelCompCases[200][8] = {"]
out += ["    {" + ", ".join(f"{v:.17g}" for v in r) + "}," for r in rows]
out += ["};", ""]
Path(__file__).resolve().parents[1].joinpath("tests/data/levelcomp_cases.h").write_text("\n".join(out))
print("wrote 200 cases")
