#!/usr/bin/env python3
"""Freeze the SHOGUN stage-2 decimator coefficients (spec v2.2 section 3.4) into engine/halfband_coeffs.h.
Stage 1 (2fs -> fs, 93 taps) is the shared exact halfband jidai::dsp::Halfband93 from
third_party/jidai-common/include/jidai/dsp/Halfband.h (vendored; see VENDORED.md), so it is not generated here.
Stage 2 (4fs -> 2fs, only at 4x): 25 taps, pass 0.10625, stop 0.39375 (of the 4x rate), equiripple (Parks-McClellan),
the same design as verify_v2.py. It is a general linear-phase FIR (not exact halfband); polyphase decimation."""
import sys
import numpy as np
from scipy import signal
from pathlib import Path
def design(n, fp, fs_):
    h = signal.remez(n, [0, fp, fs_, 0.5], [1, 0], fs=1.0)
    w, H = signal.freqz(h, worN=1 << 16, fs=1.0)
    stop = -20*np.log10(np.max(np.abs(H[w >= fs_])))
    rip = 20*np.log10(np.max(np.abs(H[w <= fp]))) - 20*np.log10(np.min(np.abs(H[w <= fp])))
    return h, stop, rip
h2, s2, r2 = design(25, 0.10625, 0.39375)
print(f"stage2 25 taps: stop {s2:.2f} dB ripple {r2:.3e} dB")
out = ["#pragma once", "// Generated by scripts/gen_halfband.py. Do not edit.",
       "// Stage 1 (2fs -> fs): the shared exact halfband jidai::dsp::Halfband93 (jidai/dsp/Halfband.h), 93 taps,",
       "// delay 46 samples at 2fs = 23 base samples.",
       f"// Stage 2 (4fs -> 2fs): 25 taps, stopband {s2:.2f} dB, pass ripple {r2:.2e} dB. Delay 12 samples at 4fs = 3 base samples.",
       "namespace shogun { namespace hb {", "constexpr int kStage2Taps = 25;",
       "constexpr double kStage2[25] = {"] + [f"    {v:.17e}," for v in h2] + ["};", "}  // namespace hb", "}  // namespace shogun", ""]
dest = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parents[1].joinpath("engine/halfband_coeffs.h")
dest.write_text("\n".join(out))
