#!/usr/bin/env python3
"""Freeze the SHOGUN decimator coefficients (spec v2.2 section 3.4) into engine/halfband_coeffs.h.
Stage 1: 93 taps, pass 0.2125, stop 0.2875 (of the 2x rate). Stage 2: 25 taps, pass 0.10625, stop 0.39375 (of 4x).
Equiripple (Parks-McClellan), the same design as verify_v2.py.
The filters are general linear-phase FIRs (not exact halfband); decimation is polyphase (outputs computed at the low rate)."""
import numpy as np
from scipy import signal
from pathlib import Path
def design(n, fp, fs_):
    h = signal.remez(n, [0, fp, fs_, 0.5], [1, 0], fs=1.0)
    w, H = signal.freqz(h, worN=1 << 16, fs=1.0)
    stop = -20*np.log10(np.max(np.abs(H[w >= fs_])))
    rip = 20*np.log10(np.max(np.abs(H[w <= fp]))) - 20*np.log10(np.min(np.abs(H[w <= fp])))
    return h, stop, rip
h1, s1, r1 = design(93, 0.2125, 0.2875)
h2, s2, r2 = design(25, 0.10625, 0.39375)
print(f"stage1 93 taps: stop {s1:.2f} dB ripple {r1:.3e} dB; stage2 25 taps: stop {s2:.2f} dB ripple {r2:.3e} dB")
out = ["#pragma once", "// Generated by scripts/gen_halfband.py. Do not edit.",
       f"// Stage 1 (2fs -> fs): 93 taps, stopband {s1:.2f} dB, pass ripple {r1:.2e} dB. Delay 46 samples at 2fs = 23 base samples.",
       f"// Stage 2 (4fs -> 2fs): 25 taps, stopband {s2:.2f} dB, pass ripple {r2:.2e} dB. Delay 12 samples at 4fs = 3 base samples.",
       "namespace shogun { namespace hb {", "constexpr int kStage1Taps = 93;", "constexpr int kStage2Taps = 25;",
       "constexpr double kStage1[93] = {"] + [f"    {v:.17e}," for v in h1] + ["};", "constexpr double kStage2[25] = {"] + \
      [f"    {v:.17e}," for v in h2] + ["};", "}  // namespace hb", "}  // namespace shogun", ""]
Path(__file__).resolve().parents[1].joinpath("engine/halfband_coeffs.h").write_text("\n".join(out))
