// Factory bank tool (scripts/make_factory.py drives it).
//   factory_fmt canon IN.json OUT.inc   rewrites a JSON array of patch documents in the canonical sparse text
//                                        (patchToJson(patch, false)) as the kBank[] table of engine/factory_bank.inc
//   factory_fmt peaks IN.json BARS      renders each patch with its pattern for BARS bars at 44.1 and 48 kHz from a
//                                        fresh engine (default master) and prints {"name": peak dBFS, ...}
#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

#include "patch.h"

using namespace shogun;

namespace {

std::string slurp(const char* path) {
  std::string s;
  FILE* f = std::fopen(path, "rb");
  if (!f) return s;
  char buf[4096];
  std::size_t n;
  while ((n = std::fread(buf, 1, sizeof buf, f)) > 0) s.append(buf, n);
  std::fclose(f);
  return s;
}

// The top-level array's elements as text spans.
std::vector<std::string> elements(const std::string& text) {
  std::vector<std::string> out;
  patchjson::Reader r(text.c_str());
  r.array([&]() {
    r.ws();
    const char* a = r.p;
    r.skip();
    out.emplace_back(a, static_cast<std::size_t>(r.p - a));
  });
  if (!r.ok) out.clear();
  return out;
}

double barSamples(const Engine& e, double fs) {
  const double bpm = 40.0 + 160.0 * e.param(P_CLOCK_TEMPO);
  const int scale = stepIndex(e.param(P_CLOCK_SCALE), 4);
  const int bar = 1 + stepIndex(e.param(P_CLOCK_BAR), 32);
  return bar * 60.0 * fs / (bpm * stepsPerQuarter(scale));
}

}  // namespace

int main(int argc, char** argv) {
  if (argc < 4) return 2;
  const std::string mode = argv[1];
  const std::vector<std::string> docs = elements(slurp(argv[2]));
  if (docs.empty()) {
    std::fprintf(stderr, "factory_fmt: no patch documents in %s\n", argv[2]);
    return 1;
  }
  if (mode == "canon") {
    std::string inc =
        "// Generated by scripts/make_factory.py; tools/factory_fmt.cpp writes the canonical patch text (engine/patch.h,\n"
        "// patchToJson sparse). Do not edit by hand: change the script and run `make factory`.\n"
        "// clang-format off\n"
        "inline constexpr Entry kBank[] = {\n";
    for (const std::string& d : docs) {
      Patch p;
      if (!parsePatch(d.c_str(), p)) {
        std::fprintf(stderr, "factory_fmt: syntax error in a patch\n");
        return 1;
      }
      const std::string name = std::string(p.name).substr(4);
      inc += "{\"" + name + "\", R\"SGF(" + patchToJson(p, false) + ")SGF\"},\n";
    }
    inc += "};\n// clang-format on\n";
    FILE* f = std::fopen(argv[3], "wb");
    if (!f) return 1;
    std::fwrite(inc.data(), 1, inc.size(), f);
    std::fclose(f);
    std::printf("%d patches -> %s\n", static_cast<int>(docs.size()), argv[3]);
    return 0;
  }
  if (mode == "peaks") {
    const int bars = std::atoi(argv[3]);
    std::printf("{");
    bool first = true;
    for (const std::string& d : docs) {
      Patch p;
      if (!parsePatch(d.c_str(), p)) return 1;
      double pk = 0.0;
      for (double fs : {44100.0, 48000.0}) {
        Engine e;
        e.prepare(fs, 2);
        applyPatch(p, e);
        e.setRunning(true);
        const long n = static_cast<long>(std::ceil(bars * barSamples(e, fs)));
        for (long i = 0; i < n; ++i) {
          e.processSample();
          pk = std::fmax(pk, std::fmax(std::fabs(e.mainL()), std::fabs(e.mainR())));
        }
      }
      std::printf("%s\"%s\": %.3f", first ? "" : ", ", p.name + 4, pk > 0 ? 20.0 * std::log10(pk) : -999.0);
      first = false;
    }
    std::printf("}\n");
    return 0;
  }
  return 2;
}
