#!/usr/bin/env python3
"""Write tests/fmtg_ref.inc: correctly rounded %.*g strings (ties to even) for testPatchWriterNoLibc.

Python's format(v, '.{p}g') is correctly rounded; each string is also checked against exact Decimal arithmetic.
Run from the repository root: python3 tools/gen_fmtg_ref.py
"""
import math
import struct
from decimal import ROUND_HALF_EVEN, Decimal, getcontext

getcontext().prec = 1200


def bits(v):
    return struct.unpack('<Q', struct.pack('<d', float(v)))[0]


def exact_g(v, p):
    if v == 0:
        return '-0' if math.copysign(1.0, v) < 0 else '0'
    d = Decimal(v)
    neg = d < 0
    d = abs(d)
    x = d.adjusted()
    q = d.scaleb(-x).quantize(Decimal(1).scaleb(-(p - 1)), rounding=ROUND_HALF_EVEN)
    if q >= 10:
        x += 1
        q = (q / 10).quantize(Decimal(1).scaleb(-(p - 1)), rounding=ROUND_HALF_EVEN)
    digs = str(q).replace('.', '').rstrip('0') or '0'
    if x < -4 or x >= p:
        s = digs[0] + ('.' + digs[1:] if len(digs) > 1 else '') + 'e' + ('-' if x < 0 else '+') + '%02d' % abs(x)
    elif x >= 0:
        ip, fp = (digs + '0' * (x + 1))[:x + 1], digs[x + 1:]
        s = ip + ('.' + fp if fp else '')
    else:
        s = '0.' + '0' * (-x - 1) + digs
    return ('-' if neg else '') + s


entries = []


def add(v, ps=range(1, 18)):
    v = float(v)
    if math.isfinite(v):
        for p in ps:
            entries.append((bits(v), p, format(v, '.%dg' % p)))


for n in range(1, 40):  # the Apple trailing-zero family: 305 at p=2, 1005 at p=3, ...
    add(n * 100 + 5)
    add(-(n * 100 + 5))
    add(n * 1000 + 5)
    add(n * 10 + 5)
for v in [305.0, -305.0, 1005.0, 1050.0, 2005.0, 9995.0, 10005.0]:
    add(v)
for v in [0.0, -0.0, 1.0, 0.5, 0.1, 1.0 / 3.0, 5e-324, 2.2250738585072014e-308, 1.7976931348623157e308,
          9007199254740993.0, 123456789012345678.0, 1e-5, 1e-4, 99999.5, 100000.0, 0.00012345]:
    add(v)
for v in [0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 9.5, 99.5, 999.5, 9999.5, 99999.5,
          0.25, 1.25, 0.125, 0.0625, 9.995, 99.95, 0.09995, 0.009995]:
    add(v)
for v in [1e-4, 1e-5, 9.999e-5, 1.0001e-4, 1e-3, 9.999e-4, 1e15, 1e16, 9.999999999999999e14]:
    add(v)
for k in [-1074, -1022, -50, -10, -5, -1, 0, 1, 5, 10, 20, 50, 1023]:
    add(math.ldexp(1.0, k))
for k in range(0, 128):
    add(k / 127.0, ps=[1, 2, 3, 6, 9, 12, 15, 17])
for v in [5e-324, 1e-323, 1e-322, 4.94e-324, 2.2250738585072014e-308, 1.7976931348623157e308, 8.98846567431158e307]:
    add(v)

seen, rows = set(), []
for b, p, s in entries:
    if (b, p) in seen:
        continue
    seen.add((b, p))
    v = struct.unpack('<d', struct.pack('<Q', b))[0]
    assert exact_g(v, p) == s, (hex(b), p, s, exact_g(v, p))
    rows.append((b, p, s))

out = ['// Correctly-rounded %.*g strings (ties to even). Generated by tools/gen_fmtg_ref.py; do not edit by hand.',
       '// Compared by testPatchWriterNoLibc so the check does not depend on host libc/gdtoa.',
       'static const struct { std::uint64_t bits; int p; const char* text; } kFmtGRef[] = {']
out += ['  { 0x%016xull, %d, "%s" },' % r for r in rows]
out += ['};', 'static const int kFmtGRefN = %d;' % len(rows)]
with open('tests/fmtg_ref.inc', 'w') as f:
    f.write('\n'.join(out) + '\n')
print('tests/fmtg_ref.inc: %d entries' % len(rows))
